name: AutoGenerateRulesForQX

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'  # Runs every 3 days at midnight UTC

jobs:
  generate_qx_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout qx branch
      uses: actions/checkout@v2
      with:
        ref: qx

    - name: Create /opt directory if not exists
      run: sudo mkdir -p /opt

    - name: Download assets
      run: |
        sudo curl -L -o /opt/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
        sudo curl -L -o /opt/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
        sudo curl -L -o /opt/geoview_linux_amd64 https://github.com/snowie2000/geoview/releases/latest/download/geoview_linux_amd64
        sudo chmod +x /opt/geoview_linux_amd64

    - name: Generate rules
      run: |
        /opt/geoview_linux_amd64 -input /opt/geosite.dat -action convert -list gfw -type geosite -format qx -output /home/runner/work/geoview/geoview/gfw.conf
        /opt/geoview_linux_amd64 -input /opt/geoip.dat -action convert -list telegram,cloudflare -append -type geosite -format qx -output /home/runner/work/geoview/geoview/gfw.conf
        /opt/geoview_linux_amd64 -input /opt/geosite.dat -action convert -list 'geolocation-!cn' -type geosite -format qx -output /home/runner/work/geoview/geoview/global.conf
        /opt/geoview_linux_amd64 -input /opt/geoip.dat -action convert -list telegram,cloudflare -append -type geosite -format qx -output /home/runner/work/geoview/geoview/global.conf
        /opt/geoview_linux_amd64 -input /opt/geosite.dat -action convert -list 'cn' -type geosite -format qx -output /home/runner/work/geoview/geoview/cn.conf
        /opt/geoview_linux_amd64 -input /opt/geosite.dat -action convert -list 'category-ads' -type geosite -format qx -output /home/runner/work/geoview/geoview/ads.conf

    - name: Check for changes
      id: changes
      run: |
        git add gfw.conf global.conf ads.conf cn.conf
        if git diff --cached --quiet; then
          echo "No changes to commit"
          echo "changed=false" >> $GITHUB_ENV
        else
          echo "Changes detected"
          echo "changed=true" >> $GITHUB_ENV
        fi
        
    - name: Commit and push changes
      if: env.changed == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add gfw.conf global.conf ads.conf cn.conf
        git commit -m "Update rules - $(date -u +'%Y-%m-%d %H:%M:%S')"
        git push origin qx
