name: AutoGenerateRulesForQX

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'  # Runs every 3 days at midnight UTC

jobs:
  download_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout qx branch
      uses: actions/checkout@v2
      with:
        ref: qx

    - name: Create /opt directory if not exists
      run: sudo mkdir -p /opt

    - name: Download geosite.dat
      run: sudo curl -L -o /opt/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

    - name: Download geoview executable
      run: sudo curl -L -o /opt/geoview_linux_amd64 https://github.com/snowie2000/geoview/releases/latest/download/geoview_linux_amd64

    - name: Make geoview executable
      run: sudo chmod +x /opt/geoview_linux_amd64

    - name: Run geoview command for gfw.conf
      run: /opt/geoview_linux_amd64 -input /opt/geosite.dat -action convert -list gfw -type geosite -format qx -output /home/runner/work/geoview/geoview/gfw.conf

    - name: Run geoview command for global.conf
      run: /opt/geoview_linux_amd64 -input /opt/geosite.dat -action convert -list 'geolocation-!cn' -type geosite -format qx -output /home/runner/work/geoview/geoview/global.conf

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add gfw.conf global.conf
        git commit -m "Update rules - $(date -u +'%Y-%m-%d %H:%M:%S')"
        git push origin qx
